## Glossary of terms

- Classification
- Regression
- Hyperparameters
- Hyperparameter search
- Autoencoder
- Convolutional Neural Network
- Recurrent Neural Network
- LSTM
- GRU
- GAN
- VAE
- CNN
- RNN
- Activation Function
- Softmax
- SGD
- Batch normalization
- Error/Loss/Cost
- Backpropagation
- Gradient Descent
- Training Loss
- Validation Loss
- Training data
- Validation data
- Test data
- Auto-regressive
- Dropout
- Regularization
- Model Capacity
- Overfitting
- Underfitting
- Supervised Learning
- Unsupervised Learning
- Adversarial Learning
- Generalization